Repository osuTitanic/wiki, pull requests merged in 2024-11, with the labels that each got.

#34 Update `Wiki`
  wiki/en.md
Labels: expansion

#35 Add additional languages on osu!mania member in `BAT` article
  wiki/People/BAT/en.md
Labels: expansion

#36 Add `Verified users`
  wiki/People/Verified_Users/en.md
Labels: new

#32 add `Levi` wiki article
  wiki/People/Levi/en.md
Labels: new, wip

#40 Add `Chicony` to Verified People
  wiki/People/Verified_Users/en.md
Labels: expansion

#41 Add Mapset Total Drain Time Requirement to Ranking Criteria
  wiki/Ranking_Criteria/en.md
Labels: expansion, ranking criteria

#42 Add Digitalfear117 in `Wiki maintainers` page
  wiki/People/Wiki_maintainers/en.md
Labels: expansion

#43 Add broilertm on `BAT` page
  wiki/People/BAT/en.md
Labels: expansion

#45 Move wrn81056 to previous `BAT` members
  wiki/People/BAT/en.md
Labels: expansion
