Repository osuTitanic/wiki, pull requests merged in 2024-10, with the labels that each got.

#15 [RU] Add wiki
  wiki/Rules/ru.md
  wiki/ru.md
Labels: translation

#26 Update BAT list to include the new BATs
  wiki/People/BAT/en.md
Labels: expansion

#25 Add `Wiki maintainers` page
  wiki/People/Wiki_maintainers/en.md
Labels: new

#27 Add uppercase in `Rules`
  wiki/Rules/en.md
Labels: spelling

#31 Update `BAT`
  wiki/People/BAT/en.md
Labels: update, spelling, expansion
