Repository osuTitanic/wiki, pull requests merged in 2024-12, with the labels that each got.

#46 Add broilertm in `Verified users`
  wiki/People/Verified_Users/en.md
Labels: expansion

#37 Add `Playtesters` page
  wiki/People/Testers/en.md
Labels: new

#48 Add Combo Colour Luminosity to RC
  wiki/Ranking_Criteria/en.md
Labels: expansion, ranking criteria

#49 Update `Early Passengers`
  wiki/People/Early_passengers/en.md
Labels: update, expansion
