Repository osuTitanic/wiki, pull requests merged in 2025-07, with the labels that each got.

#87 Update `Verified Users`
  wiki/People/Verified_Users/en.md
Labels: expansion

#88 Update `BAT`
  wiki/People/Alumni/en.md
  wiki/People/BAT/en.md
Labels: expansion

#90 Rework "Rules" page
  wiki/Rules/en.md
Labels: expansion

#95 Update `Verified Users` & `BAT`
  wiki/People/BAT/en.md
  wiki/People/Verified_Users/en.md
Labels: expansion

#96 Update `BAT`
  wiki/People/BAT/en.md
Labels: expansion

#97 Add `Tournament Management Team` & Update `Verified Users`
  wiki/People/Tournament_Management_Team/en.md
  wiki/People/Verified_Users/en.md
Labels: new, expansion

#98 Update `Verified Users`
  wiki/People/Verified_Users/en.md
Labels: expansion

#100 Change the description in `Verified Users`
  wiki/People/Verified_Users/en.md
Labels: update

#99 Add AI rule in `Ranking Criteria`
  wiki/Ranking_Criteria/en.md
Labels: expansion, ranking criteria
